server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      routes:
        - id: trip-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/trips/**
          filters:
            - name: CircuitBreaker
            - args:
              name: tripServiceCircuitBreaker
              fallbackUri: forward:/fallback
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
        - id: place-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/places/**
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
        - id: recommendation-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/recommendations/**
        - id: traveller-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/travellers/**
        - id: ai-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/ai/**
        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notifications/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      tripServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3